#!/usr/bin/env bash
# ██████╗ ██████╗  ██████╗ ███╗   ███╗██████╗ ████████╗███████╗
# ██╔══██╗██╔══██╗██╔═══██╗████╗ ████║██╔══██╗╚══██╔══╝██╔════╝
# ██████╔╝██████╔╝██║   ██║██╔████╔██║██████╔╝   ██║   ███████╗
# ██╔═══╝ ██╔══██╗██║   ██║██║╚██╔╝██║██╔═══╝    ██║   ╚════██║
# ██║     ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║        ██║   ███████║
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝        ╚═╝   ╚══════╝

# if [ "$color_prompt" = yes ]; then
#   PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
#   PS1='$ '
#   export PS1="\w\n\\$ \[$(tput sgr0)\]"
#   export PS1="[\w] \\$ \[$(tput sgr0)\]"
# else
#   PS5='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
# fi
# 
# unset color_prompt force_color_prompt
# 
# If this is an xterm set the title to user@host:dir
# case "$TERM" in
# xterm*|rxvt*)
#   PS5="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
#   ;;
# *)
#   ;;
# esac

export PS1="$(git_get_branch_if_repo) \[\033[38;5;11m\]\$(parse_current_dir) \\$ \[$(tput sgr0)\]"
#export PS1=$(lolcat_prompt)
#PROMPT_COMMAND=lolcat_prompt
#PROMPT_COMMAND=$git_config
#export PS1=$(git_prompt)
